package dev.delewer.letstroll.text;

import java.util.LinkedHashMap;
import java.util.Map;

public final class Lang {

    private static final Map<String, String> ENGLISH = new LinkedHashMap<>();

    static {
        ENGLISH.put("prefix", "<gradient:#a855f7:#ec4899>[Let's Troll]</gradient> ");
        ENGLISH.put("hub.title", "<dark_gray>LetsTroll");
        ENGLISH.put("hub.tab.players.title", "<aqua>Players");
        ENGLISH.put("hub.tab.players.description", "<gray>Pick a player and troll them");
        ENGLISH.put("hub.tab.players.online", "<gray>Online: <white>{0}");
        ENGLISH.put("hub.tab.events.title", "<light_purple>Events");
        ENGLISH.put("hub.tab.events.description", "<gray>Scheduled and triggered trolls");
        ENGLISH.put("hub.tab.bindings.title", "<gold>Bindings");
        ENGLISH.put("hub.tab.bindings.description", "<gray>Bind trolls to items and keys");
        ENGLISH.put("hub.tab.settings.title", "<green>Settings");
        ENGLISH.put("hub.tab.settings.description", "<gray>Plugin configuration");
        ENGLISH.put("hub.tab.modes.title", "<gold>Modes");
        ENGLISH.put("hub.tab.modes.description", "<gray>Special linked-player game modes");
        ENGLISH.put("modes.chain.name", "<gold>Chained together");
        ENGLISH.put("modes.chain.description", "<gray>Two players share a chain, inventory, health and death");
        ENGLISH.put("modes.chain.length", "<green>Chain length <gray>{0} blocks");
        ENGLISH.put("modes.chain.length.adjust", "<dark_gray>Click to cycle 15 / 20 / 25 / 30");
        ENGLISH.put("modes.chain.link", "<green>Link the two selected players");
        ENGLISH.put("modes.chain.link.hint", "<gray>They will share everything and be tethered");
        ENGLISH.put("modes.chain.linked", "<green>Players chained together.");
        ENGLISH.put("modes.chain.unlinked", "<yellow>Chain removed.");
        ENGLISH.put("modes.chain.entry.select", "<yellow>Click to select for linking");
        ENGLISH.put("modes.chain.entry.selected", "<aqua>Selected (click to unselect)");
        ENGLISH.put("modes.chain.entry.linked", "<green>Chained with <white>{0}");
        ENGLISH.put("modes.chain.entry.unlink", "<dark_gray>Right click to unlink");
        ENGLISH.put("modes.chain.mode", "<gold>Link <gray>{0}");
        ENGLISH.put("modes.chain.mode.adjust", "<dark_gray>Click to cycle rigid / elastic / rubber");
        ENGLISH.put("modes.chain.mode.rigid", "rigid");
        ENGLISH.put("modes.chain.mode.rigid.hint", "<gray>Hits the end of the chain like a wall");
        ENGLISH.put("modes.chain.mode.elastic", "elastic");
        ENGLISH.put("modes.chain.mode.elastic.hint", "<gray>Pulls back smoothly the further they stray");
        ENGLISH.put("modes.chain.mode.rubber", "rubber");
        ENGLISH.put("modes.chain.mode.rubber.hint", "<gray>Builds up and slingshots them back together");
        ENGLISH.put("modes.chain.visual", "<green>Visible chain");
        ENGLISH.put("modes.chain.visual.hint", "<gray>Draw the sagging chain between the two");
        ENGLISH.put("modes.chain.style", "<gold>Drawn as <gray>{0}");
        ENGLISH.put("modes.chain.style.hint", "<dark_gray>Click to switch between real links and particles");
        ENGLISH.put("modes.chain.style.links", "real chain links");
        ENGLISH.put("modes.chain.style.particles", "particles");
        ENGLISH.put("modes.chain.inertia", "<green>Momentum");
        ENGLISH.put("modes.chain.inertia.hint", "<gray>A running player really drags the other one");
        ENGLISH.put("common.back", "<yellow>Back");
        ENGLISH.put("common.close", "<red>Close");
        ENGLISH.put("common.previous", "<yellow>Previous page");
        ENGLISH.put("common.next", "<yellow>Next page");
        ENGLISH.put("common.page", "<gray>Page <white>{0}</white> of <white>{1}</white>");
        ENGLISH.put("common.search", "<yellow>Search a player");
        ENGLISH.put("common.search.prompt", "<gray>Type a nickname");
        ENGLISH.put("common.search.active", "<gray>Filter: <white>{0}");
        ENGLISH.put("common.search.clear", "<gray>Leave the field empty to clear it");
        ENGLISH.put("common.toggle.on", "<green>● Enabled <gray>(click to turn off)");
        ENGLISH.put("common.toggle.off", "<red>● Disabled <gray>(click to turn on)");
        ENGLISH.put("common.no-permission", "<red>You are not allowed to do that.");
        ENGLISH.put("common.players-only", "<red>Only a player can run this.");
        ENGLISH.put("common.player-not-found", "<red>Player <white>{0}</white> was not found.");
        ENGLISH.put("players.title", "<dark_gray>Players");
        ENGLISH.put("players.empty", "<gray>Nobody is online right now");
        ENGLISH.put("players.empty.filtered", "<gray>No player matches <white>{0}");
        ENGLISH.put("players.entry.world", "<gray>World: <white>{0}");
        ENGLISH.put("players.entry.ping", "<gray>Ping: <white>{0} ms");
        ENGLISH.put("players.entry.health", "<gray>Health: <white>{0}");
        ENGLISH.put("players.entry.hint", "<yellow>Click to open the action menu");
        ENGLISH.put("player.title", "<dark_gray>{0}");
        ENGLISH.put("player.actions.empty", "<gray>No actions are registered yet");
        ENGLISH.put("player.actions.hint", "<gray>Add a module folder to get more actions");
        ENGLISH.put("events.toggle", "<green>Automatic events");
        ENGLISH.put("events.interval", "<green>Interval <gray>{0} min");
        ENGLISH.put("events.interval.adjust", "<dark_gray>Click to change (1-30 min)");
        ENGLISH.put("events.bossbar", "<green>Timer bar <gray>{0}");
        ENGLISH.put("events.bossbar.adjust", "<dark_gray>Click to cycle OFF / ADMINS / ALL");
        ENGLISH.put("events.fire-now", "<gold>Fire an event now");
        ENGLISH.put("events.fire-now.hint", "<gray>Runs one random enabled event");
        ENGLISH.put("events.fired", "<green>A random event was fired.");
        ENGLISH.put("events.entry.dangerous", "<red>Dangerous");
        ENGLISH.put("events.entry.safe", "<gray>Safe");
        ENGLISH.put("events.entry.fire", "<dark_gray>Right click to fire it now");
        ENGLISH.put("events.bar.title", "<light_purple>Next event in <white>{0}s");
        ENGLISH.put("events.entry.jumpscare", "<white>Jumpscare");
        ENGLISH.put("events.entry.random_effects", "<white>Random effects");
        ENGLISH.put("events.entry.fake_chat", "<white>Fake chat message");
        ENGLISH.put("events.entry.fake_lag", "<white>Fake lag for everyone");
        ENGLISH.put("events.entry.mob_crowd", "<white>Mob crowd");
        ENGLISH.put("events.entry.fall_to_bedrock", "<white>Fall to bedrock");
        ENGLISH.put("events.entry.chunk_wipe", "<white>Wipe the chunk");
        ENGLISH.put("events.entry.real_boom", "<white>Real explosion");
        ENGLISH.put("events.entry.swap", "<white>Swap two players");
        ENGLISH.put("events.reveal.header", "<gray>Next Event:");
        ENGLISH.put("events.entry.scramble_inventory", "<white>Scramble inventory");
        ENGLISH.put("events.entry.launch_up", "<white>Launch up");
        ENGLISH.put("events.entry.random_tp", "<white>Random teleport");
        ENGLISH.put("events.entry.gather", "<white>Gather everyone");
        ENGLISH.put("events.entry.scatter", "<white>Scatter everyone");
        ENGLISH.put("events.entry.gift", "<white>Free gift");
        ENGLISH.put("events.entry.item_rain", "<white>Item rain");
        ENGLISH.put("events.entry.heal_feed", "<white>Full heal");
        ENGLISH.put("events.entry.fireworks", "<white>Firework show");
        ENGLISH.put("events.entry.freeze_all", "<white>Freeze");
        ENGLISH.put("events.entry.speed_chaos", "<white>Speed chaos");
        ENGLISH.put("events.entry.anonymous", "<white>Anonymous");
        ENGLISH.put("events.entry.spin", "<white>Spin");
        ENGLISH.put("events.entry.fake_creeper", "<white>Fake creeper");
        ENGLISH.put("events.entry.swap_inventory", "<white>Swap inventories");
        ENGLISH.put("events.entry.storm_night", "<white>Storm and night");
        ENGLISH.put("events.entry.glowing", "<white>Glowing");
        ENGLISH.put("bindings.held", "<gray>Held item binding: <white>{0}");
        ENGLISH.put("bindings.held.hint", "<gray>Right click a player with the item to run it");
        ENGLISH.put("bindings.bind.hint", "<yellow>Click to bind to the item in your hand");
        ENGLISH.put("bindings.bound", "<green>Bound to the held item");
        ENGLISH.put("bindings.not-bound", "<gray>Not on the held item");
        ENGLISH.put("bindings.clear", "<red>Clear the binding");
        ENGLISH.put("bindings.saved", "<green>Bound <white>{0}</white> to the held item.");
        ENGLISH.put("bindings.cleared", "<yellow>Binding removed from the held item.");
        ENGLISH.put("bindings.none", "<gray>The held item has no binding.");
        ENGLISH.put("bindings.hold-item", "<red>Hold an item to bind an action to it.");
        ENGLISH.put("effects.pick.title", "<dark_gray>Pick an effect");
        ENGLISH.put("effects.pick.hint", "<yellow>Click to apply it to <white>{0}");
        ENGLISH.put("effects.applied", "<green>Applied <white>{0}</white> to <white>{1}</white>.");
        ENGLISH.put("effects.action.effects", "<light_purple>Potion effects");
        ENGLISH.put("effects.action.effects.desc", "<gray>Pick a nasty effect for the player");
        ENGLISH.put("effects.action.scare", "<light_purple>Scare");
        ENGLISH.put("effects.action.scare.desc", "<gray>Scream and short darkness");
        ENGLISH.put("effects.scared", "<green>Scared <white>{0}</white>.");
        ENGLISH.put("effects.action.fake_lightning", "<light_purple>Fake lightning");
        ENGLISH.put("effects.action.fake_lightning.desc", "<gray>A harmless lightning strike");
        ENGLISH.put("effects.lightning", "<green>Struck <white>{0}</white> with fake lightning.");
        ENGLISH.put("effects.action.fake_death", "<light_purple>Fake death");
        ENGLISH.put("effects.action.fake_death.desc", "<gray>Broadcast a fake death message");
        ENGLISH.put("effects.death", "<green>Faked the death of <white>{0}</white>.");
        ENGLISH.put("settings.title", "<dark_gray>Settings");
        ENGLISH.put("settings.language", "<green>Language <gray>{0}");
        ENGLISH.put("settings.modules", "<green>Modules loaded <gray>{0}");
        ENGLISH.put("settings.sounds", "<green>Menu sounds");
        ENGLISH.put("settings.sounds.description", "<gray>Play a sound on open and click");
        ENGLISH.put("settings.hide-plugins", "<green>Hide from /plugins");
        ENGLISH.put("settings.hide-plugins.description", "<gray>Ordinary players cannot see LetsTroll listed");
        ENGLISH.put("settings.hide-commands", "<green>Hide the commands");
        ENGLISH.put("settings.hide-commands.description", "<gray>/troll and /ghost stay out of tab completion");
        ENGLISH.put("settings.reload", "<yellow>Reload configuration");
        ENGLISH.put("settings.reload.done", "<green>Configuration reloaded.");
        ENGLISH.put("ghost.action.name", "<aqua>Ghost mode");
        ENGLISH.put("ghost.action.on", "<gray>Currently: <green>on");
        ENGLISH.put("ghost.action.off", "<gray>Currently: <red>off");
        ENGLISH.put("ghost.action.hint", "<yellow>Click to toggle it for yourself");
        ENGLISH.put("ghost.enabled.self", "<green>Ghost mode enabled. Nobody can see you.");
        ENGLISH.put("ghost.disabled.self", "<yellow>Ghost mode disabled. You are visible again.");
        ENGLISH.put("ghost.enabled.other", "<green>Ghost mode enabled for <white>{0}</white>.");
        ENGLISH.put("ghost.disabled.other", "<yellow>Ghost mode disabled for <white>{0}</white>.");
        ENGLISH.put("ghost.usage", "<gray>Usage: <white>/ghost [on|off|<player>] [on|off]");
        ENGLISH.put("mannequin.title", "<dark_gray>Fake player");
        ENGLISH.put("mannequin.action.name", "<gold>Fake player");
        ENGLISH.put("mannequin.action.description", "<gray>Drop a nameless copy of a player in front of them");
        ENGLISH.put("mannequin.action.presets", "<gray>Presets: <white>{0}");
        ENGLISH.put("mannequin.preset.skin", "<gray>Skin: <white>{0}");
        ENGLISH.put("mannequin.preset.mirror", "the victim itself");
        ENGLISH.put("mannequin.preset.hint", "<yellow>Click to show it to <white>{0}");
        ENGLISH.put("mannequin.spawned", "<green>Preset <white>{0}</white> is now standing in front of <white>{1}</white>.");
        ENGLISH.put("mannequin.clear", "<red>Remove the fake players");
        ENGLISH.put("mannequin.cleared", "<yellow>Removed every fake player near <white>{0}</white>.");
        ENGLISH.put("mannequin.preset.remove", "<dark_gray>Right click to delete (admin)");
        ENGLISH.put("mannequin.add.name", "<green>Add a preset");
        ENGLISH.put("mannequin.add.hint", "<gray>Click and type it in chat");
        ENGLISH.put("mannequin.add.prompt", "<gray>Type: <white>id nick_or_link</white> (name, profile link, texture hash or base64)");
        ENGLISH.put("mannequin.add.usage", "<red>Format: <white>id skin</white>, for example <white>steve Notch</white>");
        ENGLISH.put("mannequin.added", "<green>Preset <white>{0}</white> saved.");
        ENGLISH.put("mannequin.removed", "<yellow>Preset <white>{0}</white> deleted.");
        ENGLISH.put("lag.action.name", "<gold>Fake lag");
        ENGLISH.put("lag.action.description", "<gray>Rubberband the player and fake a high ping in tab");
        ENGLISH.put("lag.action.power", "<gray>Power: <white>{0}</white>/10");
        ENGLISH.put("lag.action.on", "<green>Running, click to stop");
        ENGLISH.put("lag.action.off", "<yellow>Left click to start");
        ENGLISH.put("lag.action.adjust", "<dark_gray>Right click to change power (1-10)");
        ENGLISH.put("lag.power", "<gray>Lag power set to <white>{0}</white>/10.");
        ENGLISH.put("lag.started", "<green>Fake lag (power {1}) started on <white>{0}</white>.");
        ENGLISH.put("lag.stopped", "<yellow>Fake lag stopped on <white>{0}</white>.");
    }

    private Lang() {
    }

    public static Map<String, String> english() {
        return Map.copyOf(ENGLISH);
    }

    public static String fallback(String key) {
        return ENGLISH.getOrDefault(key, key);
    }
}
