name: LetsTroll
version: '1.0.4'
main: org.imdel.letstroll.LetsTroll
api-version: '1.21.1'

commands:
  ghost:
    description: Manage the ghost mode for players (toggle invisibility and join/quit message suppression)
    usage: /ghost
    permission: letstroll.ghost.use
    permission-message: You do not have permission to use ghost mode commands.

  stand:
    description: Spawn predefined Armor Stands with custom appearance
    usage: /stand <stand_name> <player_name> | /stand reload
    permission: letstroll.stand.use
    permission-message: You do not have permission to use the stand command.

  tool:
    description: Tool command for trolling presets and entity summoning
    usage: /tool <bind|unbind|stand|> [arguments]
    permission: letstroll.tool.use
    permission-message: You do not have permission to use the tool commands.

permissions:
  letstroll.ghost.use:
    description: Allows the player to use ghost mode commands
    default: op

  letstroll.stand.use:
    description: Allows the player to use the stand command to spawn Armor Stands
    default: op

  letstroll.tool.use:
    description: Allows the player to use tool commands for trolling and entity summoning
    default: op
