name: 🐞 Bug Report
description: Report a bug or unexpected behavior in the LetsTroll plugin
title: "[BUG] "
labels: bug
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Please provide detailed information to help us reproduce and fix the issue.

  - type: input
    id: description
    attributes:
      label: Description
      placeholder: Describe the problem you encountered
    validations:
      required: true

  - type: input
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: List the exact steps to reproduce the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to see

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what you observed instead

  - type: input
    id: versions
    attributes:
      label: Plugin & Server Versions
      description: Please specify the LetsTroll plugin version and Minecraft server version
      placeholder: e.g. LetsTroll v1.0.4, Paper 1.21.1

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Error Messages
      description: Attach any error logs or stack traces if available
      placeholder: Paste logs here or attach files

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist before submitting
      options:
        - label: I have searched existing issues and did not find a similar bug
          required: true
        - label: I tested the latest plugin version
          required: true
        - label: I included relevant logs and version info
          required: true